apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: direct-smtp-sink
  labels:
    apps.tanzu.vmware.com/workload-type: queue
    app.kubernetes.io/part-of: direct-project
spec:
  params:
  - value:
    - containerPort: 1026
      port: 1026
    name: ports
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-1
  source:
    git:
      url: https://github.com/gm2552/direct-smtp-sink.git
      ref:
        branch: master
